Repository acm-ucr/membership-portal-admin, pull requests merged in 2022-12, with the labels that each got.

#6 Setup Repo
  components/Header.js
  pages/announcements.js
  pages/checkin.js
  pages/interviews.js
  pages/resources.js
  pages/resumes.js
Labels: repository

#7 add dockerfile
  Dockerfile
Labels: repository, ready for review

#8 add cloudbuild
  cloudbuild.yaml
Labels: repository, ready for review

#10 Fundamental Features
  components/AddAnnouncements.js
  components/AddResource.js
  components/Announcement.js
  components/Announcements.js
  components/Checkin.js
  components/Header.js
  components/Navigation.js
  components/QuickAction.js
  components/QuickActions.js
  components/Resource.js
  components/Resources.js
  package-lock.json
  package.json
  pages/announcements.js
  pages/api/addPoints.js
  pages/api/getAllAnnouncements.js
  pages/api/getAllResources.js
  pages/checkin.js
  pages/index.js
  pages/resources.js
  tailwind.config.js
Labels: ready for review

#11 welcome message complete per #1
  components/Dashboard.js
  pages/dashboard.js
Labels: dashboard, ready for review

#15 Implement frontend for adding editing and viewing announcement card
  components/AddAnnouncements.js
  components/Announcement.js
  components/Announcements.js
Labels: announcements, ready for review
