Repository acm-ucr/membership-portal-admin, pull requests merged in 2023-02, with the labels that each got.

#26 added layout component
  components/Layout.js
  pages/_app.js
  pages/index.js
Labels: repository, ready for review

#25 Create trashcan delete button on announcement.
  components/Announcement.js
Labels: announcements, ready for review

#20 Add a div class wrapped around the resource popup
  components/Resource.js
Labels: resources, ready for review

#31 Vraimondi04/delete announcement
  components/Announcement.js
  pages/api/addAnnouncement.js
  pages/api/deleteAnnouncement.js
  pages/api/updateAnnouncment.js
Labels: announcements, backend
